### ISSUE TITLE
「Linux Hostへの接続 (Jump Host を利用しない場合」のホスト名の記載

### ISSUE THREAD

**Issue by tomonori71** [hiropo20/back-to-basic_plus#1]
「Linux Hostへの接続 (Jump Host を利用しない場合」の記載で、
「k8s1 への接続はメニューより SSH をクリックしてください」とありますが、「ubuntu01」が正しいと思われます。
https://github.com/hiropo20/back-to-basic_plus#linux-host%E3%81%B8%E3%81%AE%E6%8E%A5%E7%B6%9A-jump-host-%E3%82%92%E5%88%A9%E7%94%A8%E3%81%97%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88

**Comment by hiropo20** [comment]
ご指摘ありがとうございます。該当行を削除し、修正を完了しました。
