### ISSUE TITLE
4. listen directive (10min)のコマンド実行結果

### ISSUE THREAD

**Issue by tomonori71** [hiropo20/back-to-basic_plus#2]
https://github.com/hiropo20/back-to-basic_plus#4-listen-directive-10min

cat default.conf
コマンドの実行結果に、
`# service nginx restart`
コマンドが含まれています。

**Comment by hiropo20** [comment]
不要なコマンドであったため削除しました

**Comment by tomonori71** [comment]
`# service nginx restart`　
自体は、設定反映のため必要だと思われるので、catコマンドの実行結果後に、入れたほうがよいのではないでしょうか？

**Comment by hiropo20** [comment]
失礼しました。対応します

**Comment by hiropo20** [comment]
モバイルで操作したためコメントの反映に失敗しましたが、先程修正しました。
